import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Logo from '../public/Logo.svg'
import Button from '../components/Button'
import Navbar from '../components/Navbar'
import { useSession, signOut } from 'next-auth/react'
import popServices from '../data/PopServices'
import categories from '../data/categories'
import Slider from 'react-slick'
import { motion } from 'framer-motion'
import carouselSettings from '../utils/carouselSettings'
export default function Home() {

  const { session } = useSession()
    console.log(session)

    return (
      <div>
        <Head>
          <title>Proserv</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <div className="max-w-box w-full min-h-full absolute -z-10 border-x-[1px] opacity-50 border-black left-1/2 transform -translate-x-1/2" /> */}
        <div className="container lg:text-left text-center px-4 flex flex-col items-center min-w-full font-medium">
          {/* Navbar starts */}
          <Navbar />
          {/* Navbar starts */}

          {/* HomePage main Card starts */}
          <div className="w-full gcwidth:max-w-[1370px] max-w-box lg:h-[443px] md:h-[343px] py-4 text-center lg:text-left px-8 flex justify-center items-center relative bg-lightGreen my-4 rounded-[20px] shadow-card before:bg-black">
            <div className="flex items-center justify-between w-full h-full max-w-box">
              <div className="xl:w-1/2 w-full mb-8 flex flex-col items-center lg:items-start">
                <h1 className="font-semibold lg:text-bigHeading text-4xl leading-[64px] mb-4">Struggling to find services for your business?</h1>
                <p className='lg:text-xl text-lg opacity-80'>One stop solution <br className='hidden lg:block' />for all services you need</p>
                <div className="w-3/4 h-[2px] bg-black opacity-70 rounded-sm my-7" />
                <div className="space-x-6">
                  <Button style="bg-black px-4 py-2 font-medium rounded-md text-white font-secondary" >Explore</Button>
                  <Button style="px-4 py-2 font-medium rounded-md text-black border-[1px] border-black font-secondary" >How it works</Button>
                </div>
              </div>
              <div className="mr-10 lg:block hidden">
                <Image src='/boy.svg' height="350.13" width="441" alt='boy illustration' />
              </div>
            </div>
          </div>
          {/* HomePage main Card ends */}

          {/* Popular Services Section starts */}
          <div className="w-full max-w-box mt-12 space-y-8">
            <h1 className="font-medium text-4xl">Our Popular Services</h1>
            <div className="flex flex-wrap">
              {popServices.map((service, id) => {
                return (
                  <div key={id} className="group flex flex-grow flex-shrink-0 md:max-w-[300px] w-60 items-center m-2 lg:pl-5 lg:justify-start justify-center h-40 cursor-pointer border-[1px] border-black shadow-card before:border-[2px] before:top-[-5px] before:left-[-5px] before:transition-colors before:duration-700 hover:before:border-lightGray before:border-lightGreen">
                    <h1 className='transition-all group-active:scale-95 font-semibold text-xl'>{service}</h1>
                  </div>
                )
              })}
            </div>
          </div>
          {/* Popular Services Section ends */}

          {/* Sevices Cateogories starts */}
          <div className="w-full max-w-box mt-12 space-y-8">
            <h1 className="font-medium text-4xl">Explore the services</h1>
            <Slider {...carouselSettings}>
              {categories.map((category, id) => (
                <div key={id} className="group h-40 py-6 cursor-pointer border-[1px] border-black rounded-[20px] transition-all">
                  <div className='group-active:scale-95 flex flex-col items-center transition-transform'>
                    <Image src={category.imageURL} alt='category icon' unoptimized='true' width='80' height='80' objectFit='contain' />
                    <h1 className='font-normal text-xl'>{category.name}</h1>
                  </div>
                </div>
              ))}
            </Slider>
          </div>
          {/* Sevices Cateogories ends */}


        </div>
      </div>
    )
}

export async function getStaticProps(context) {
  // const res = await fetch('https://localhost:3000/api/pservices')
  return {
    props: {}, // will be passed to the page component as props
  }
}

